artifacts_root: artifacts


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Physical_Therapy_Patient_Data.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/Physical_Therapy_Patient_Data.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_x_data_path: artifacts/data_transformation/train_x.csv
  train_y_data_path: artifacts/data_transformation/train_y.csv
  test_x_data_path: artifacts/data_transformation/test_x.csv
  test_y_data_path: artifacts/data_transformation/test_y.csv
  model_name: model.joblib


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test_x.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
  mlflow_uri: "https://dagshub.com/oldbright22/End-to-End-MLOPS-2024.mlflow"
